version: '3'
services:

  account-db:
    image: postgres:14.2
    hostname: postgres-host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5451:5432'
    volumes: 
      - ./account_data/volume:/var/lib/postgresql/data