apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: frontend-app
  name: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: frontend-app
    spec:
      containers:
        - env:
            - name: REACT_APP_ACCOUNT_URL
              value: http://localhost:9091
            - name: REACT_APP_INVENTORY_URL
              value: http://localhost:9094
            - name: REACT_APP_ORDER_URL
              value: http://localhost:9095
            - name: REACT_APP_PAYMENT_URL
              value: http://localhost:9096
            - name: REACT_APP_SHIPMENT_URL
              value: http://localhost:9093
          image: frontend
          name: frontend-app
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
