apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: inventory-db
  name: inventory-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: inventory-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: inventory-db
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres:14.2
          name: inventory-db
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
