apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: order-app
  name: order-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: order-app
    spec:
      containers:
        - env:
            - name: INVENTORY_URL
              value: http://inventory-app:9094
            - name: NOTIFICATION_URL
              value: http://notification-app:9092
            - name: PAYMENT_URL
              value: http://payment-app:9096
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_HOST
              value: order-db
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_SLLMODE
              value: disable
            - name: POSTGRES_TIMEZONE
              value: America/Sao_Paulo
            - name: POSTGRES_USER
              value: postgres
            - name: SHIPMENT_URL
              value: http://shipment-app:9093
          image: order
          name: order-app
          ports:
            - containerPort: 9095
              protocol: TCP
      restartPolicy: Always
